# This is a basic workflow to help you get started with Actions

name: CI

on:
    issue_comment:
        types: [created]

jobs:
    create_issue_branch_job:
        runs-on: ubuntu-latest
        steps:
        - name: Create Issue Branch
          uses: robvanderleek/create-issue-branch@v1.4
          env:
            GITHUB_TOKEN: ${{ secrets.GOD_TOKEN }}
